name: moyen_paiement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 📌 Ajout des dépendances pour le scanner QR et les permissions
  mobile_scanner: ^3.4.1
  permission_handler: ^11.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mastercard.png
    - assets/visa.png
    - assets/amex.png
    - assets/discover.png
    - assets/qr_code_example.png
    - assets/phone_frame.png
    - assets/wave.png
